services:
  app:
    build:
      context: ./
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - type: bind
        source: "./"
        target: "/app"
      - type: bind
        source: "./node_modules"
        target: "/app/node_modules"
    command: sh -c "npm run dev"
volumes:
  node_modules: