services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./web:/web
      # - /web/node_modules:/web/node_modules
    command: sh -c "npm run dev"
volumes:
  node_modules:
